// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_content_delivery_bucket: 'bim-dev-aws-amplify-bucket',
  aws_content_delivery_bucket_region: 'eu-west-1',
  aws_content_delivery_url:
    'http://bim-dev-aws-amplify-bucket.s3-website-eu-west-1.amazonaws.com',
  aws_cognito_identity_pool_id:
    'eu-west-1:9e625e5b-1be2-4125-8b9b-dac41db4f99d',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_c7EdEEuIx',
  aws_user_pools_web_client_id: '5iqlsvr9908r3nc5rme8vg4uit',
}

export default awsmobile
