// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_content_delivery_bucket: 'bim-dev-aws-amplify-bucket',
  aws_content_delivery_bucket_region: 'eu-west-1',
  aws_content_delivery_url:
    'http://bim-dev-aws-amplify-bucket.s3-website-eu-west-1.amazonaws.com',
}

export default awsmobile
